global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['flask-app:9000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
